AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Backend Serverless Todo App
Globals:
  Function:
    Timeout: 10
    Runtime: python3.12
    Environment:
      Variables:
        TABLE_NAME:
          Ref: TasksTable
  Api:
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'*'"
Resources:
  ServerlessRestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
  TasksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: TasksTable
      AttributeDefinitions:
      - AttributeName: userId
        AttributeType: S
      - AttributeName: taskId
        AttributeType: S
      KeySchema:
      - AttributeName: userId
        KeyType: HASH
      - AttributeName: taskId
        KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
  CreateTaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://artifacts-manolo-pro-v1/cb3e69dd533069db03f0996c7b119416
      Handler: app.lambda_handler
      Policies:
      - AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME:
            Ref: TasksTable
      Events:
        CreateTaskApi:
          Type: Api
          Properties:
            Path: /tasks
            Method: post
            RestApiId:
              Ref: ServerlessRestApi
  GetTasksFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://artifacts-manolo-pro-v1/cb3e69dd533069db03f0996c7b119416
      Handler: get_tasks.lambda_handler
      Policies:
      - AmazonDynamoDBReadOnlyAccess
      Environment:
        Variables:
          TABLE_NAME:
            Ref: TasksTable
      Events:
        GetTasksApi:
          Type: Api
          Properties:
            Path: /tasks
            Method: get
            RestApiId:
              Ref: ServerlessRestApi
  UpdateTaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://artifacts-manolo-pro-v1/cb3e69dd533069db03f0996c7b119416
      Handler: update_task.lambda_handler
      Policies:
      - AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME:
            Ref: TasksTable
      Events:
        UpdateTaskApi:
          Type: Api
          Properties:
            Path: /tasks/{taskId}
            Method: put
            RestApiId:
              Ref: ServerlessRestApi
  DeleteTaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://artifacts-manolo-pro-v1/cb3e69dd533069db03f0996c7b119416
      Handler: delete_task.lambda_handler
      Policies:
      - AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME:
            Ref: TasksTable
      Events:
        DeleteTaskApi:
          Type: Api
          Properties:
            Path: /tasks/{taskId}
            Method: delete
            RestApiId:
              Ref: ServerlessRestApi
Outputs:
  WebEndpoint:
    Description: URL de la API Gateway
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
