AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "Backend Serverless Todo App"

# --- CONFIGURACIÓN GLOBAL (Aplica a todas las funciones y APIs) ---
Globals:
  Function:
    Timeout: 10
    Runtime: python3.12
    Environment:
      Variables:
        TABLE_NAME: !Ref TasksTable
  Api:
    # Esto habilita CORS para toda la API automáticamente
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'*'"

Resources:
  # --- BASE DE DATOS ---
  TasksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: TasksTable
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: taskId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: taskId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  # --- FUNCIÓN 1: CREAR TAREA ---
  CreateTaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/
      Handler: app.lambda_handler
      Policies:
        - AmazonDynamoDBFullAccess
      Events:
        CreateTaskApi:
          Type: Api
          Properties:
            Path: /tasks
            Method: post

  # --- FUNCIÓN 2: LEER TAREAS ---
  GetTasksFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/
      Handler: get_tasks.lambda_handler
      Policies:
        - AmazonDynamoDBReadOnlyAccess
      Events:
        GetTasksApi:
          Type: Api
          Properties:
            Path: /tasks
            Method: get

Outputs:
  WebEndpoint:
    Description: "URL de la API Gateway"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
