AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "Backend Serverless Todo App"

# --- CONFIGURACIÓN GLOBAL (Aplica a todas las funciones y APIs) ---
Globals:
  Function:
    Timeout: 10
    Runtime: python3.12
    Environment:
      Variables:
        TABLE_NAME: !Ref TasksTable
  Api:
    # Esto habilita CORS para toda la API automáticamente
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'*'"

Resources:
  # --- API EXPLÍCITA ---
  ServerlessRestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

  # --- BASE DE DATOS ---
  TasksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: TasksTable
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: taskId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: taskId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  # --- FUNCIÓN 1: CREAR ---
  CreateTaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/
      Handler: app.lambda_handler
      Policies:
        - AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: !Ref TasksTable
      Events:
        CreateTaskApi:
          Type: Api
          Properties:
            Path: /tasks
            Method: post
            RestApiId: !Ref ServerlessRestApi

  # --- FUNCIÓN 2: LEER ---
  GetTasksFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/
      Handler: get_tasks.lambda_handler
      Policies:
        - AmazonDynamoDBReadOnlyAccess
      Environment:
        Variables:
          TABLE_NAME: !Ref TasksTable
      Events:
        GetTasksApi:
          Type: Api
          Properties:
            Path: /tasks
            Method: get
            RestApiId: !Ref ServerlessRestApi

  # --- FUNCIÓN 3: ACTUALIZAR ---
  UpdateTaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/
      Handler: update_task.lambda_handler
      Policies:
        - AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: !Ref TasksTable
      Events:
        UpdateTaskApi:
          Type: Api
          Properties:
            Path: /tasks/{taskId}
            Method: put
            RestApiId: !Ref ServerlessRestApi

  # --- FUNCIÓN 4: BORRAR ---
  DeleteTaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/
      Handler: delete_task.lambda_handler
      Policies:
        - AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: !Ref TasksTable
      Events:
        DeleteTaskApi:
          Type: Api
          Properties:
            Path: /tasks/{taskId}
            Method: delete
            RestApiId: !Ref ServerlessRestApi

Outputs:
  WebEndpoint:
    Description: "URL de la API Gateway"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
